import { PublicKey } from '@solana/web3.js';
import { NATIVE_MINT } from '@solana/spl-token';

// MagicBlock PER Configuration
// Using TEE endpoint for Private Ephemeral Rollup authentication
export const MAGICBLOCK_PER_RPC = 'https://tee.magicblock.app';
// Official MagicBlock validator (from https://github.com/magicblock-labs/private-payments-demo)
export const MAGICBLOCK_VALIDATOR = new PublicKey('FnE6VJT5QNZdedZPnCoLsARgBwoE6DeJNjBs2H1gySXA');
export const MAGICBLOCK_PROGRAM = new PublicKey('EnhkomtzKms55jXi3ijn9XsMKYpMT4BJjmbuDQmPo3YS');

// MagicBlock's official Private Payments Program (with TEE/PER support)
export const PRIVATE_PAYMENTS_PROGRAM = new PublicKey('EnhkomtzKms55jXi3ijn9XsMKYpMT4BJjmbuDQmPo3YS');

// PDA Seeds (must match MagicBlock's official program: EnhkomtzKms55jXi3ijn9XsMKYpMT4BJjmbuDQmPo3YS)
export const DEPOSIT_PDA_SEED = 'deposit';
export const VAULT_PDA_SEED = 'vault';

// Session duration (5 minutes)
export const SESSION_DURATION = 5 * 60 * 1000;

// Supported vault assets (devnet)
// Auto-generated by mint-vault-tokens script on 2025-10-25T10:19:41.586Z
export const VAULT_ASSETS = {
  USDC: new PublicKey('4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU'), // Standard devnet USDC (users deposit this)
  USDC_PLUS: new PublicKey('GKeVmB9GoYG3GSRHbYxBEQtLCpXkHWx6a2Vk6d2nwnvu'), // senUSDC+ (Sen Yield)
  SOL: new PublicKey('Af6k6HREWTT6TLUbX11U8TJkACc3SfVfp8tUXtyXWizj'), // senSOL (Sen Solana) - NEW
  WETH: new PublicKey('HQu26wRQBy9N38m1nFjaNuYSn4VfFYGfr6BCGR98czuv'), // senETH (Sen Ethereum) - NEW
  ZBTC: new PublicKey('3rtGQMzjV5LQnSN77GB5zhDKriEt4WnwBvBPtGfrFWSz'), // senBTC (Sen Bitcoin) - NEW
  GLDX: new PublicKey('Gn3a9oBUf5iQQ4KhjdnumLeTgmKRqeDxqi37Y4YtgmS5'), // senGOLD (Sen Gold) - NEW
  NVDA: new PublicKey('7akrhpLdZs7EyUU1Vd5HnVBzb1bKyXxFPKw9Hp1EYNpJ'), // senNVDA (Sen NVIDIA) - NEW
} as const;

// For mainnet deployment, replace with actual addresses:
// USDC_PLUS: Reflect token (TBD)
// WETH: 7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs (Wormhole)
// ZBTC: zBTCug3er3tLyffELcvDNrKkCymbPWysGcWihESYfLg (Zeus Network)
// GLDX: (TBD)
// NVDA: NVDAx from Jupiter xStocks (TBD)

export type VaultAsset = keyof typeof VAULT_ASSETS;

// Asset decimals
export const ASSET_DECIMALS: Record<VaultAsset, number> = {
  USDC: 6,
  USDC_PLUS: 6,
  SOL: 9,
  WETH: 8,
  ZBTC: 8,
  GLDX: 6,
  NVDA: 6,
};

// Allocation presets
export const ALLOCATION_PRESETS = {
  conservative: {
    name: 'Conservative',
    description: 'Low risk, stable yield',
    allocations: {
      usdc: 20,
      usdcPlus: 80,
      sol: 0,
      weth: 0,
      zbtc: 0,
      gldx: 0,
      nvda: 0,
    },
  },
  balanced: {
    name: 'Balanced',
    description: 'Balanced risk/reward',
    allocations: {
      usdc: 30,
      usdcPlus: 30,
      sol: 20,
      weth: 0,
      zbtc: 10,
      gldx: 0,
      nvda: 10,
    },
  },
  growth: {
    name: 'Growth',
    description: 'Higher risk, growth + tech focus',
    allocations: {
      usdc: 5,
      usdcPlus: 15,
      sol: 30,
      weth: 15,
      zbtc: 10,
      gldx: 0,
      nvda: 25,
    },
  },
} as const;

export type AllocationPreset = keyof typeof ALLOCATION_PRESETS;
